spring.config.import: classpath:external-secret.yml
spring.profiles.active: prod

spring:
  servlet:
    multipart:
      enabled: false

hive:
  uploadDir: C:\Users\YLiang\Downloads\hive\upload\
  downloadDir: C:\Users\YLiang\Downloads\hive\download\