spring.config.import: classpath:external-secret.yml
spring.profiles.active: test

hive:
  sync:
    uploadDir: C:\Users\YLiang\Downloads\hive\upload\
    downloadDir: C:\Users\YLiang\Downloads\hive\download\